Repository bside-dev-club/B-TIL, pull requests merged in 2023-05, with the labels that each got.

#3 [1기]1주차 황지원
  1기/1주차/황지원_230505.md
Labels: btil-1, bside-15, checked

#4 [1기] 1주차 양동선
  guide/1주차/양동선_230503.md
  guide/1주차/양동선_230505.md
  guide/1주차/양동선_230506.md
Labels: btil-1, bside-15, checked

#5 [1기] 1주차 윤효정(미션O)
  1기/1주차/윤효정_230502.md
  1기/1주차/윤효정_230504.md
Labels: btil-1, bside-15, checked

#6 [1기]1주차 황시우 (미션O)
  1기/1주차/황시우_230503.md
  1기/1주차/황시우_230504.md
Labels: btil-1, bside-15, checked

#7 [manage] 파일 위치 정리 / 2주차 폴더 생성
  1기/1주차/양동선_230503.md
  1기/1주차/양동선_230505.md
  1기/1주차/양동선_230506.md
  1기/2주차/.gitkeep
Labels: manage

#11 [1기]2주차 황지원-1
  1기/2주차/황지원_230511.md
  1기/3주차/황지원_230515.md
  1기/3주차/황지원_230516.md
Labels: btil-1, bside-15, checked

#10 [1기] 2주차 윤효정(미션X)
  1기/1주차/윤효정_230504.md
  1기/2주차/윤효정_230509.md
  1기/2주차/윤효정_230512.md
  1기/2주차/윤효정_230514.md
Labels: btil-1, bside-15, checked

#9 [1기] 2주차 최연서
  1기/2주차/최연서_230511.md
  1기/2주차/최연서_230514.md
Labels: btil-1, bside-15, checked

#8 [1기]2주차 양동선 (미션O)
  1기/2주차/양동선_230510.md
  1기/2주차/양동선_230512.md
  1기/2주차/양동선_230513.md
Labels: btil-1, bside-15, checked

#16 [1기] 3주차 윤효정
  1기/3주차/윤효정_230516.md
  1기/3주차/윤효정_230519.md
Labels: btil-1, bside-15

#15 [1기]3주차 황지원-3
  1기/3주차/황지원_230516.md
Labels: btil-1, bside-15, checked

#12 [1기]3주차 양동선 (미션O)
  1기/3주차/양동선_230517.md
  1기/3주차/양동선_230519.md
Labels: btil-1, bside-15, checked

#17 [manage] 파일 위치 정리 / 4주차 폴더 생성
  1기/4주차/.gitkeep
Labels: manage
